<div class="page-header">
    <h1>Edit</h1>
</div>
<form method="POST" action="<?php echo $block->getUrl('*/*/save/post_id/'.$block->getEditRecord()['post_id'])?>">
    <div class="form-group">
        <label>Name</label>
        <input type="text" class="form-control" value="<?php echo $block->getEditRecord()['name']?>" name="name" placeholder="Enter name">
    </div>
    <div class="form-group">
        <label>URL key</label>
        <input type="text" class="form-control" value="<?php echo $block->getEditRecord()['url_key']?>" name="url_key" placeholder="Enter url key">
    </div>
    <div class="form-group">
        <label>Content</label>
        <input type="text" class="form-control" value="<?php echo $block->getEditRecord()['post_content']?>" name="post_content" placeholder="Enter content">
    </div>
    <div class="form-group">
        <label>Tags</label>
        <input type="text" class="form-control" value="<?php echo $block->getEditRecord()['tags']?>" name="tags" placeholder="Enter tags">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
